# Generated by Django 5.1.4 on 2025-01-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliasToCreator',
            new_name='AliasToArtist',
        ),
    ]
