# Generated by Django 5.1.4 on 2025-01-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_aliastocreator_aliastoartist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aliastoartist',
            old_name='alias_id',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='aliastoartist',
            old_name='creator_id',
            new_name='creator',
        ),
    ]
