# Generated by Django 5.1.4 on 2025-01-03 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_rename_alias_id_aliastoartist_alias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='creator_alias_id',
            new_name='creator_alias',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='game_name',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='chart',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='chartaliastocreator',
            old_name='alias_id',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='chartaliastocreator',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='artist_alias_id',
            new_name='artist_alias',
        ),
    ]
